[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://dakshesh.co.in"
  NEXT_PUBLIC_FORMSPREE_ENDPOINT = "https://formspree.io/f/xrevwraj"
