import { SITE_URL, person, experience, currentRole, sameAs } from "./site";
import { skillGroups, products, type Project } from "./data";
import { productContent } from "./products-content";

/**
 * JSON-LD builders. Everything is server-rendered into a
 * <script type="application/ld+json"> tag so crawlers and AI agents
 * read it without running JavaScript. No em dashes in any string.
 */

const PERSON_ID = `${SITE_URL}/#person`;
const WEBSITE_ID = `${SITE_URL}/#website`;

const knowsAbout = Array.from(
  new Set([
    "Frontend web development",
    "Web engineering",
    "Flutter development",
    "Full stack development",
    ...skillGroups.flatMap((group) => group.skills),
  ])
);

export function personSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": PERSON_ID,
    name: person.name,
    alternateName: ["Dakshesh", "Dakshesh B"],
    givenName: person.firstName,
    jobTitle: [
      "Frontend Web Developer",
      "Web Engineer",
      "Frontend Developer",
      "Flutter Developer",
      "Full Stack Developer",
      "Founder of MyKavo",
    ],
    description:
      "Dakshesh B, also known as Dakshesh, is a frontend web developer, web engineer, Flutter developer and full stack developer based in Kotagiri, India. He builds fast, accessible, high-performance web interfaces and ships full web products end to end.",
    url: `${SITE_URL}/`,
    // Real photo (valid raster image for the schema.org image property).
    image: `${SITE_URL}${person.image}`,
    email: `mailto:${person.email}`,
    telephone: person.phoneHref,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Kotagiri",
      addressRegion: "Tamil Nadu",
      addressCountry: "IN",
    },
    worksFor: {
      "@type": "Organization",
      name: currentRole.company,
      url: currentRole.companyUrl,
    },
    // Previous employer (Oct 2024 to Jul 2026).
    alumniOf: {
      "@type": "Organization",
      name: experience.company,
      url: experience.companyUrl,
    },
    knowsAbout,
    sameAs,
  };
}

export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    name: `${person.name} Portfolio`,
    url: `${SITE_URL}/`,
    inLanguage: "en",
    publisher: { "@id": PERSON_ID },
  };
}

export function profilePageSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    url: `${SITE_URL}/`,
    name: `${person.name} - ${person.role}`,
    isPartOf: { "@id": WEBSITE_ID },
    about: { "@id": PERSON_ID },
    mainEntity: { "@id": PERSON_ID },
  };
}

export function breadcrumbSchema(
  trail: { name: string; url: string }[]
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: trail.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

export function projectSchema(project: Project) {
  const base = {
    "@context": "https://schema.org",
    "@type": project.schemaType,
    name: project.title,
    description: project.metaDescription,
    url: `${SITE_URL}/work/${project.slug}`,
    // Raster PNG generated by the work opengraph-image route.
    image: `${SITE_URL}/work/${project.slug}/opengraph-image`,
    creator: { "@id": PERSON_ID },
    author: { "@id": PERSON_ID },
  };

  if (project.schemaType === "WebSite") {
    return base;
  }

  // Software and mobile applications get extra app fields.
  return {
    ...base,
    applicationCategory:
      project.schemaType === "MobileApplication"
        ? "MultimediaApplication"
        : "DeveloperApplication",
    operatingSystem:
      project.schemaType === "MobileApplication" ? "Android" : "Chrome",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
  };
}

export function productSchema(slug: string) {
  const product = products.find((p) => p.id === slug);
  const content = productContent[slug];
  if (!product || !content) return null;

  return {
    "@context": "https://schema.org",
    "@type": content.schemaType,
    name: product.name,
    description: content.metaDescription,
    url: `${SITE_URL}/${product.id}`,
    image: `${SITE_URL}/${product.id}/opengraph-image`,
    applicationCategory: content.applicationCategory,
    operatingSystem: content.platform,
    creator: { "@id": PERSON_ID },
    author: { "@id": PERSON_ID },
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    sameAs: product.url,
  };
}

export function faqSchema(items: { question: string; answer: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((it) => ({
      "@type": "Question",
      name: it.question,
      acceptedAnswer: { "@type": "Answer", text: it.answer },
    })),
  };
}
